name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Pull-Push Docker Image
        run: |
          docker pull vaibhav5252/dev-task-master:latest 
          docker tag vaibhav5252/dev-task-master:latest vaibhav5252/prod-task-master:latest 
          docker push vaibhav5252/prod-task-master:latest 
          
      - name: Deploy to k8s
        uses: tale/kubectl-action@v1
        with:  
          base64-kube-config: ${{ secrets.KUBE_CONFIG_PROD }}
      - run: |
          kubectl apply -f deployment-service.yml
