name: CICD

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: Trivy fs scan
      run: trivy fs --format table -o fs.html .

    - name: Sonar-scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    -  name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build Image
      run: |
        docker build -t vaibhav5252/dev-task-master:latest .

    - name: Trivy fs scan
      run: sudo trivy image --format table -o image.html vaibhav5252/dev-task-master:latest    
    
    - name: Push Docker Image
      run: |
        docker push vaibhav5252/dev-task-master:latest 

    - name: Deploy to k8s
      uses: tale/kubectl-action@v1
      with:  
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
    - run: |
        kubectl apply -f deployment-service.yml
